Suggest additional types-* packages from typeshed (#13698)
Now we have suggestions for almost all the currently available
third-party packages in typeshed that don't have a release that includes
PEP 561 type information. `sqlalchemy` is not included, since it has a
few alternatives (some outside typeshed), and I don't know which we
should suggest.

These stubs were never bundled with mypy, so `--ignore-missing-imports`
works with these, unlike the existing packages for which we have
suggestions.

Here's an example mypy output:
```
t.py:1: error: Library stubs not installed for "tree_sitter"
t.py:1: note: Hint: "python3 -m pip install types-tree-sitter"
t.py:1: note: (or run "mypy --install-types" to install all missing stub packages)
t.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

I manually tested that `--install-types` works for these.